### ISSUE TITLE
**Exporting does not work**

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#130]
Hey there again, I'm using the latest master CATS plugin, the latest release of the KKBP plugin, and also Blender 3.0
After fixing the shaders and colours, the next step is to Prepare for Export.
However, when I press the VRM option, it gives me an error almost immediately.

Prepping for export...

Combining all objects...

Removing object outline modifier...

Removing duplicate Eye materials...
Using CATS to simplify bones...
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\exporting\selectbones.py", line 73, in execute
    bpy.ops.cats_manual.merge_weights()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.cats_manual.merge_weights.poll() failed, context is incorrect

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\exporting\selectbones.py", line 73, in execute
    bpy.ops.cats_manual.merge_weights()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.cats_manual.merge_weights.poll() failed, context is incorrect

location: <unknown location>:-1

**It also leaves me with this mess:**

![image](https://user-images.githubusercontent.com/54001645/158280511-afd30cd7-858a-44e0-a5b3-b5da05a448b4.png)

Is anyone able to help? I've gotten past all of my problems and this is my final one ^^'

**Comment by BTHP5** [comment]
I've also tried manually fixing the model's armature with the CATs plugin as the KKBP plugin isn't doing it and it needs to do that to progress with step 3 (converting), and after I do, KKBP gives me an error that it can't find the bones it needs... So I'm pretty stuck right now :(

**Comment by BTHP5** [comment]
Does anyone have any theories or solutions?
