### ISSUE TITLE
Problem with Converting and applying shaders

### ISSUE THREAD

**Issue by Ventinian** [FlailingFog/KK-Blender-Porter-Pack#131]
When I try to convert and apply colors to shaders, I end up with this error message

Python: Traceback (most recent call last):
  File "C:\Users\jkuhl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\jkuhl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\jkuhl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

**Comment by MediaMoots** [comment]
#129 #125 
A fix will come soon, but for now please use Blender 3.0

**Comment by Ventinian** [comment]
Okay.  Thanks!

**Comment by g0g5** [comment]
having the same problem on 2.93 and 3.0, is there anything wrong among all versions (include 3.0)?

**Comment by MediaMoots** [comment]
closed for #125
