### ISSUE TITLE
When i try to convert and apply colors to shades it doesn't work

### ISSUE THREAD

**Issue by StefanoVR17** [FlailingFog/KK-Blender-Porter-Pack#143]
X Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming Blender Foundation Blender3.1\scripts addonskKK Blender-Porter-Pack-master importing importcolors.py", line 727, in execute
convert main texturesílut light)
File "C:\Users\User\AppData\Roaming Blender Foundation Blender 3.1\scripts addons KK-Blender-Porter-Pack-master importing importcolors.py", line 479, in convert_main_textures
image_to_KK'image, lut_light)
File "C:\Users\User\AppData\Roaming Blender Foundation Blender 3.1\scripts addons\KK-Blender-Porter-Pack-master importing importcolors.py", line 90, in image_to_KK
shader = gpu.types.GPUShader( vertex_default, current_code)
Exception: Shader Compile Error, see console for more details
location: <unknown location: 1

**Comment by MediaMoots** [comment]
closed in favor of #125
