### ISSUE TITLE
Shader Compile Error

### ISSUE THREAD

**Issue by 0w0-Yui** [FlailingFog/KK-Blender-Porter-Pack#162]
blender 3.1 

Python: Traceback (most recent call last):
  File "C:\Users\31056\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\31056\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\31056\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

**Comment by MediaMoots** [comment]
Fixed in #138
