### ISSUE TITLE
Shader compile error when converting and applying colors to shader

### ISSUE THREAD

**Issue by anonymousPer2** [FlailingFog/KK-Blender-Porter-Pack#178]
[This](https://illusioncards.booru.org/index.php?page=post&s=view&id=80367) is the card that made me realize the issue, but I also tried with one of the preinstalled ones (attached below) and it also had the same issue.

Blender 3.2 (also tried with 3.1) and KKBP V5.1.1

>Python: Traceback (most recent call last):
  File "C:\Users\anon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 727, in execute
    convert_main_textures(lut_light)
  File "C:\Users\anon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 479, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\anon\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 90, in image_to_KK
    shader = gpu.types.GPUShader(vertex_default, current_code)
Exception: Shader Compile Error, see console for more details

![Wild](https://user-images.githubusercontent.com/94017686/173234682-c65338a7-576b-48b6-b4f1-4979b1d52630.png)

**Comment by FlailingFog** [comment]
There's an incompatibility with 5.1.1 and 3.1+ (it's in the release notes)
Check #125 out for some more details

**Comment by anonymousPer2** [comment]
it really couldn't have been more obvious than you made it, I should learn to read patch notes more often. sorry and thank you, it was making me crazy. blender 3.0.1 was the solution.
