### ISSUE TITLE
Blender Plugin will not Finalise my specific PMX?

### ISSUE THREAD

**Issue by BTHP5** [FlailingFog/KK-Blender-Porter-Pack#179]
Hey there! I'm using the latest version of the plugin, and blender 3.0.0, and the plugin works great, except it won't Finalise the PMX (step 1) for a certain model. 
This character is a male model with the default face/head option.
It has a few accessories, however, even in different occasions, the blender plugin refuses to Finalise the PMX, here's what the blender console gives:

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\elise\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\finalizepmx.py", line 899, in execute
    bpy.ops.kkb.shapekeys('INVOKE_DEFAULT')
  File "D:\Blender Foundation\blender-3.0.0-windows-x64\3.0\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\elise\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\shapekeys.py", line 436, in execute
    combine_shapekeys(keep_partial_shapekeys)
  File "C:\Users\elise\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\shapekeys.py", line 306, in combine_shapekeys
    shapekey_block = bpy.data.shape_keys[body.data.shape_keys.name].key_blocks
AttributeError: 'NoneType' object has no attribute 'name'

location: D:\Blender Foundation\blender-3.0.0-windows-x64\3.0\scripts\modules\bpy\ops.py:130

location: <unknown location>:-1

Any help would be greatly appreciated! It can export other male models just fine, even with modded heads/faces.
![image](https://user-images.githubusercontent.com/54001645/173583841-ed6375b7-1f52-4558-b6f6-abe8937df8b1.png)

**Comment by FlailingFog** [comment]
Are there any shapekeys when you import it? That might cause it to fail if there are none.

**Comment by MediaMoots** [comment]
Pretty sure that's the old addon there.

**Comment by BTHP5** [comment]
When importing the addon, it says it's version 5.1.0, but the file I imported is 5.1.1, not sure what's going on with that.
It doesn't look like he has any shapekeys, is there a way I can fix that?
