### ISSUE TITLE
Can't finalize pmx

### ISSUE THREAD

**Issue by kmrdcyka** [FlailingFog/KK-Blender-Porter-Pack#184]
Card Link: https://drive.google.com/file/d/17JgGsgeAL-nwtCN4qmth_4F78WjfxBqv/view

I'm trying to finalize the pmx but this happens

Python: Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\finalizepmx.py", line 903, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT')
  File "D:\SteamLibrary\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\separatebody.py", line 174, in execute
    base_name, dupe_number = mat.name.split('.',2)
ValueError: too many values to unpack (expected 2)

location: D:\SteamLibrary\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py:130

location: <unknown location>:-1

**Comment by FlailingFog** [comment]
I feel like I already fixed this at some point. Are you using the 5.1.1 version?

**Comment by kmrdcyka** [comment]
yeah i'm using 5.1.1

**Comment by FlailingFog** [comment]
This wasn't in 5.1.1 as I originally thought
It should work in the V6 beta
