### ISSUE TITLE
Issue with Apply Baked Templates

### ISSUE THREAD

**Issue by DJLarpus** [FlailingFog/KK-Blender-Porter-Pack#191]
I get the following issue when attempting to apply baked templates:
Python: Traceback (most recent call last):
  File "Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\exporting\applymaterials.py", line 162, in execute
    replace_images(folderpath, apply_type)
  File "Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\exporting\applymaterials.py", line 121, in replace_images
    bpy.data.images[imageName].pack()
KeyError: 'bpy_prop_collection[key]: key "Template Face 1024x1024 light.png" not found'

The named file does exist in the folder that "bake material templates" exported to.
Hair and all accessories have been separated. Everything seemed ok until then.

[20220701101011_HarunoChika.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9032032/20220701101011_HarunoChika.zip)

**Comment by FlailingFog** [comment]
Try using the PR branch plugin, it should work in that version
