### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#196]
Some cards work some do not this is the error I get 

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\-\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 509, in execute
    separate_everything(context)
  File "C:\Users\-\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 129, in separate_everything
    bpy.data.objects[outfit.name + '.001'].name = 'Hair ' + outfit.name
KeyError: 'bpy_prop_collection[key]: key "Outfit 00.001" not found'

https://drive.google.com/file/d/1uRWXjDci78A31aZ_JgfNUsKoaXW59L3V/view?usp=sharing
Card Link

**Comment by LegionInstaller** [comment]
I should add that I'm using the latest version of pluginupdate
https://github.com/MediaMoots/KK-Blender-Shader-Pack/tree/pluginupdate

**Comment by LegionInstaller** [comment]
And Now I'm getting 2 new Erros 

Python: Traceback (most recent call last):
  File "C:\Users\Elias\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importbuttons.py", line 160, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT')
  File "D:\blender-3.1.0-windows-x64\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Elias\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 942, in execute
    if modify_armature and bpy.data.objects['Armature'].pose.bones["Spine"].custom_shape == None:
KeyError: 'bpy_prop_collection[key]: key "Spine" not found'



location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Elias\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importbuttons.py", line 160, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT')
  File "D:\blender-3.1.0-windows-x64\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Elias\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 942, in execute
    if modify_armature and bpy.data.objects['Armature'].pose.bones["Spine"].custom_shape == None:
KeyError: 'bpy_prop_collection[key]: key "Spine" not found'



location: <unknown location>:-1

**Comment by poisenbery** [comment]
Would like to 2nd this as well because I have ran into similar issue
![KK_110730](https://user-images.githubusercontent.com/78466408/179119421-89d49d83-e499-4c20-84e9-96ad8f275c59.png)

**Comment by FlailingFog** [comment]
> Some cards work some do not this is the error I get

I don't know why but it was trying to separate something twice. I put a try catch so it will import now

> have ran into similar issue with this card

I put another try catch so this will import now
