### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by kmrdcyka** [FlailingFog/KK-Blender-Porter-Pack#205]
Python: Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa\importing\importbuttons.py", line 76, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "D:\SteamLibrary\steamapps\common\Blender\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa\importing\separatebody.py", line 469, in execute
    separate_everything(context)
  File "C:\Users\muham\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-422d8b9b76070523f5ac2bb8d2d2aeb157d8c3fa\importing\separatebody.py", line 139, in separate_everything
    bpy.data.objects['Clothes.001'].name = 'Hair'
KeyError: 'bpy_prop_collection[key]: key "Clothes.001" not found'

location: <unknown location>:-1

i got this error when trying with this card
![84006228_p2](https://user-images.githubusercontent.com/92239253/179339798-5598aff5-5a54-449e-9af5-31eaf4d23eea.png)

hope u can fix this, thanks

oh btw i'm using this version
https://github.com/FlailingFog/KK-Blender-Porter-Pack/releases/tag/V6beta

**Comment by MediaMoots** [comment]
Could you try the latest V6?

Thanks!
