### ISSUE TITLE
Baking Error

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#229]
Happens on All Cards 

Error: Unknown python error occurred
Traceback (most recent call last):
File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\exporting\bakematerials.py", line 451, in execute
cleanup()
File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\exporting\bakematerials.py", line 391, in cleanup
fillerplane.select_set(True)
RuntimeError: Error: Object 'fillerplane.001' can't be selected because it is not in View Layer 'ViewLayer'!

**Comment by LegionInstaller** [comment]
Also happens with the Base Card

**Comment by FlailingFog** [comment]
The baking buttons, atlas generation and export fbx button have been working for me on the PR branch
![image](https://user-images.githubusercontent.com/65811931/187093530-278e11e3-92ae-4ce3-9afa-57b6c9db8a30.png)

**Comment by LegionInstaller** [comment]
weird

**Comment by LegionInstaller** [comment]
I've been using Blender 3.22 , does it matter tho ?

**Comment by LegionInstaller** [comment]
Nope still getting 

I'm gonna try getting a earlier version of blender

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\exporting\bakematerials.py", line 451, in execute
    cleanup()
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\exporting\bakematerials.py", line 391, in cleanup
    fillerplane.select_set(True)
RuntimeError: Error: Object 'fillerplane.001' can't be selected because it is not in View Layer 'ViewLayer'!

**Comment by LegionInstaller** [comment]
Yeah no Idea why even with 3.1 It still happens

**Comment by LegionInstaller** [comment]
Aight disabling all of my addons fixed the problem , just gotta find out which one thx
