### ISSUE TITLE
Outift not found error

### ISSUE THREAD

**Issue by sleepymanakete** [FlailingFog/KK-Blender-Porter-Pack#230]
Trying to import Byleth gives me this error. I'm using beta 6.0 and the setting i have on were "export variations and single outfit".  
card (i used her timeskip/green hair version) and mod: https://mega.nz/folder/txoQVIqb#nGLdj2zDHouT7z7cv_YxZw
and error:
```
Python: Traceback (most recent call last):
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importbuttons.py", line 88, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 506, in execute
    newVar.targets[0].id_type = 'KEY'
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 129, in separate_everything
    bpy.ops.object.mode_set(mode = 'OBJECT')
KeyError: 'bpy_prop_collection[key]: key "Outfit 00.001" not found'
```
I also had this issue with a different card until I updated to the better repack version then the pmx stopped exporting like in #147

**Comment by poisenbery** [comment]
It seems that "Single Outfit Export" was never tested on anything other than the 1st outfit in the slot.
It will produce an error if used on anything other than the 1st outfit.

**Comment by MediaMoots** [comment]
Yeah, the beta will not work with the new "Single Outfit Export" because the blender plugin used to assume that all the outfits were present, so the PR is being worked on to fix this issue.

**Comment by MediaMoots** [comment]
Does it work now? the master branch has been updated.

**Comment by sleepymanakete** [comment]
Thank you for the update. I tried it and sadly it does not. It gave me this error now:
``Python: Traceback (most recent call last):
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 91, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\inzan\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-master\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment
``

**Comment by MediaMoots** [comment]
Could you share the card please? Thanks!

**Comment by sleepymanakete** [comment]
yeah sure. np!
card is the 3rd pic here https://www.pixiv.net/en/artworks/96609288

**Comment by MediaMoots** [comment]
@FlailingFog 
It seems that this character's hair is a bit iffy, any ideas?

**Comment by LegionInstaller** [comment]
> @FlailingFog 
> It seems that this character's hair is a bit iffy, any ideas?
> 
> It fails to find hair then fails at the outline section.

Try the Outline option in the Panel

**Comment by MediaMoots** [comment]
It now works on the latest master.
