### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Template Face 1024x1024 light.png"

### ISSUE THREAD

**Issue by mangguo68** [FlailingFog/KK-Blender-Porter-Pack#231]
I promise, I have made sure that there is this file in my folder.
However, once I click “Apply baked templates” button, I will report an error.
Python: Traceback (most recent call last):
  File "C:\Users\mangguo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\exporting\applymaterials.py", line 162, in execute
    replace_images(folderpath, apply_type)
  File "C:\Users\mangguo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-master\exporting\applymaterials.py", line 121, in replace_images
    bpy.data.images[imageName].pack()
KeyError: 'bpy_prop_collection[key]: key "Template Face 1024x1024 light.png" not found'
How to solve it?

**Comment by FlailingFog** [comment]
This was fixed a while back but I forgot when
