### ISSUE TITLE
Outfit is not defined and Object has not Attribute , RuntimeError: Error: Nothing selected

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#236]
Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 1171, in execute
    texture_error = get_and_load_textures(directory)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 524, in get_and_load_textures
    if '_m_body_AM_' in image.name and outfit.name[-1:].isnumeric():
NameError: name 'outfit' is not defined

Only some cards give this error

Can be fixed my Copying the AM_some number and changing it to 00

**Comment by LegionInstaller** [comment]
Update: Happens with every card now

**Comment by LegionInstaller** [comment]
Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 1177, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\importeverything.py", line 941, in add_outlines
    mod.thickness = 0.0005
AttributeError: 'UVWarpModifier' object has no attribute 'thickness'

**Comment by LegionInstaller** [comment]
Another one

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 697, in execute
    separate_everything(context)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 174, in separate_everything
    separate_material(outfit, hair_mat_list)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Shader-Pack-pluginupdate\importing\separatebody.py", line 126, in separate_material
    bpy.ops.mesh.separate(type='SELECTED')
  File "D:\blender-3.2.2-stable+v32.bcfdb14560e7-windows.amd64-release\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

**Comment by poisenbery** [comment]
I've been getting this issue on some cards as well.

![KK_110730](https://user-images.githubusercontent.com/78466408/188291327-b5c9c78a-9e52-4f5e-92c3-103cab0c33c5.png)


Sample card that produces import errors.

**Comment by LegionInstaller** [comment]
> I've been getting this issue on some cards as well.
> 
> ![KK_110730](https://user-images.githubusercontent.com/78466408/188291327-b5c9c78a-9e52-4f5e-92c3-103cab0c33c5.png)
> 
> Sample card that produces import errors.

What kind of Error are you getting ?

**Comment by poisenbery** [comment]
> What kind of Error are you getting ?

"Nothing Selected" on blender import

**Comment by poisenbery** [comment]
@LegionInstaller It has something to do with the clothing textures.

I believe that they have a different naming convention from other textures, specifically with clothing.

I was able to get the model to successfully import into blender by selecting "Naked" in KK so they export with empty outfits.


Still trying to isolate exactly what is causing this bug.

**Comment by MediaMoots** [comment]
@FlailingFog 

![image](https://user-images.githubusercontent.com/81146974/188347773-05b5d237-d611-47fb-9418-2acb82223210.png)
The issue is most likely caused by this variable not being defined. 
Maybe the code broke when the new outfit numbering system was added?

**Comment by LegionInstaller** [comment]
> @FlailingFog 
> 
> ![image](https://user-images.githubusercontent.com/81146974/188348231-39a84e03-4b18-44da-8c10-f075cc388376.png)
> The issue is most likely caused by this variable not being defined. 
> Maybe the code broke when the new outfit numbering system was added?

The AM Issue can be fixed by changing it  to AM_00 if Single Outfit and the Modifier by choosing the option in the KKBP Import Panel

**Comment by FlailingFog** [comment]
outfit.name was supposed to be image.name. I changed that part to something else in https://github.com/FlailingFog/KK-Blender-Porter-Pack/pull/138/commits/a5ca4938eac7702a4c2d80222f87236742f31844
