### ISSUE TITLE
Attempting to finish categorization produces an error.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#255]
> Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment
>
>Error: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment
>
>Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importbuttons.py", line 164, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment
>
>Error: Python: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importbuttons.py", line 164, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment

**Comment by LegionInstaller** [comment]
Use single outline until fixed

**Comment by BugMonkey42335** [comment]
After doing some testing I found this error came from the hair object being called Outfit ## Hair instead of Hair Outfit ##.
