### ISSUE TITLE
some card will stops working

### ISSUE THREAD

**Issue by confusionkd** [FlailingFog/KK-Blender-Porter-Pack#263]
Blender 3.3, KKBP 6.0 Koikatsu HF patch 3.17

After importing, error report pops up and then stops working.
![擷取](https://user-images.githubusercontent.com/114286744/192097702-e8b9693a-8dee-407c-9613-91eb989965fd.PNG)

error:
Python: Traceback (most recent call last):
  File "C:\Users\confusionkd\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importbuttons.py", line 91, in execute
    bpy.ops.kkb.importeverything('INVOKE_DEFAULT'),
  File "D:\Blender Foundation\blender-3.3.0-windows-7\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\confusionkd\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 1254, in execute
    add_outlines(single_outline_mode)
  File "C:\Users\confusionkd\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack-V6-0-0\importing\importeverything.py", line 982, in add_outlines
    mod.material_offset = outlineStart
UnboundLocalError: local variable 'outlineStart' referenced before assignment

card:
https://drive.google.com/file/d/1phKR5rhPHBhkqHHwyeqI5iZ7kr6Q7vF9/view?usp=sharing
or
https://www.pixiv.net/artworks/96469722

**Comment by LegionInstaller** [comment]
Click the Outline Option in the KKBP Panel until fixed

**Comment by FlailingFog** [comment]
This card imports correctly on the master branch now

**Comment by confusionkd** [comment]
thank you for your dedication!
