### ISSUE TITLE
LBS Shader Nodes that are created by the KKBP have broken transparency 

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#285]
Importing a model with the LBS Shader option connects the alpha to the shader but the shader it creates doesn't have working transparency
Adding the LBS shader manually and replacing the one in the node group works but the KKBP one always remains broken
![image](https://user-images.githubusercontent.com/101014618/194859423-926a1781-d0f0-43fc-90b8-821a92fc521b.png)

KKBP addon downloaded from master
LBS Addon is 2.1.3
KKBP log with only the relevant part

> Traceback (most recent call last):
  File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\lbsnode.py", line 28, in init
    self.on_init( context )
  File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\shader_node.py", line 44, in on_init
    mat["is_lbs_material"] = True
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\lbsnode.py", line 14, in prop_update_initialize_group
    self.update_node_group( context )
  File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\lbsnode.py", line 95, in update_node_group
    self.on_update_node_group( context )
  File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\shader_node.py", line 23, in on_update_node_group
    self.update_transparency( not material.blend_method == "OPAQUE" )
AttributeError: 'NoneType' object has no attribute 'blend_method'
File "C:\Users\WindowsUser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\lightning_boy_shader\nodes\lbsnode.py", line 13, in prop_update_initialize_group
LBS: Material not found
Warning: 1 x Draw window and swap: 7865.1950 ms, average: 7865.19500008 ms
Finished in 20.5s

**Comment by FlailingFog** [comment]
I fixed the transparency but i'm not getting the error you pasted above
