### ISSUE TITLE
Fancy Face Types causing blender import error

### ISSUE THREAD

**Issue by poisenbery** [FlailingFog/KK-Blender-Porter-Pack#302]
Cards that use any of the "fancy" face types [actual lips/nose] throw an error in blender.
The "Fancy" face types are circled in red.
![Screenshot (1000)](https://user-images.githubusercontent.com/78466408/197902577-16b53000-2741-4b16-971a-0821e25c77c4.png)

```
Python: Traceback (most recent call last):
  File "C:\Users\austi\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack\importing\importbuttons.py", line 91, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\austi\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack\importing\separatebody.py", line 621, in execute
    make_tear_and_gag_shapekeys()
  File "C:\Users\austi\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack\importing\separatebody.py", line 375, in make_tear_and_gag_shapekeys
    separate_materials(body, tearMats)
  File "C:\Users\austi\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\KK-Blender-Porter-Pack\importing\separatebody.py", line 94, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "D:\Steam\steamapps\common\Blender\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected
```

Sample card that uses a "fancy face type"
![KK_292901](https://user-images.githubusercontent.com/78466408/197902758-c4c7208e-8f53-4b5f-9b10-309886f43c87.png)

**Comment by poisenbery** [comment]
After some investigation, it seems that the naming convention of the face materials cause it to get lumped in with clothing/accessories. 
![Screenshot (1002)](https://user-images.githubusercontent.com/78466408/197946459-4407a71d-6724-41c2-97fc-a5ea45a979bd.png)

**Comment by poisenbery** [comment]
@MediaMoots This seems to be on the dll plugin side of things. I did a raw import of the PMX; the body PMX does not contain the face mesh at all. The clothing PMX does.

**Comment by poisenbery** [comment]
@FlailingFog "Fancy face types" have a different naming convention for the face material. I'm not 100% sure, but I think that a catch for this would need to be added to ensure that it gets properly detected by the blender side of things. I noticed the scripts had a catch for face2 for the same reason.
![Screenshot (1002)](https://user-images.githubusercontent.com/78466408/197948142-6ba974ce-f112-4463-a283-28a0c3212a38.png)

**Comment by MediaMoots** [comment]
> @MediaMoots This seems to be on the dll plugin side of things. I did a raw import of the PMX; the body PMX does not contain the face mesh at all. The clothing PMX does.

Thank you for checking!

**Comment by poisenbery** [comment]
> Thank you for checking!

NP. Thanks for releasing a PR so quickly!
I'm trying to work on a fix for the blender side, but it seems as if my python knowledge isn't good enough :D
