### ISSUE TITLE
KeyError: 'color' while calculating colors

### ISSUE THREAD

**Issue by MRtecno98** [FlailingFog/KK-Blender-Porter-Pack#330]
While importing the exported PMX file it begins to load fine but at the end crashes while(i guess) calculating the dark colors, with a `KeyError: 'color'` error. Stacktrace and full blender logs from start to finish below.

## Stacktrace

```
Error: Traceback (most recent call last):
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 773, in execute
    convert_main_textures(lut_light)
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 496, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 104, in image_to_KK
    batch = batch_for_shader(
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\gpu_extras\batch.py", line 62, in batch_for_shader
    attr_len = recommended_attr_len(name)
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\gpu_extras\batch.py", line 39, in recommended_attr_len
    item = content[attr_name][0]
KeyErTraceback (most recent call last):
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importbuttons.py", line 89, in execute
    bpy.ops.kkb.importcolors('EXEC_DEFAULT'),
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 773, in execute
    convert_main_textures(lut_light)
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 496, in convert_main_textures
    image_to_KK(image, lut_light)
  File "C:\Users\Giorgio\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\importing\importcolors.py", line 104, in image_to_KK
    batch = batch_for_shader(
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\gpu_extras\batch.py", line 62, in batch_for_shader
    attr_len = recommended_attr_len(name)
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\gpu_extras\batch.py", line 39, in recommended_attr_len
    item = content[attr_name][0]
KeyError: 'color'
```

[Full blender logs](https://pastebin.com/raw/9wEZqFRc)

## Software versions

- KKBP Exporter v3.98
- KKBP Blender Plugin v6.2.1
- Blender v3.4.1
- Koikatsu BetterRepack R6 + HF Patch v3.15 (and kPlug)

## Card used
![Koikatu_F_20230102211400699_Player_collas](https://user-images.githubusercontent.com/20360363/210408909-f714314b-0444-4f7f-84f6-7471af38b902.png)

**Comment by FlailingFog** [comment]
I see what happened. There was a change between Blender 3.3.2 and Blender 3.4.0 that broke the importcolors.py script. The script imports a function from Blender/modules/gpu_extras/batch.py that is different between the two versions. This will most likely be an easy fix.

**Comment by MRtecno98** [comment]
Can confirm it is fixed! Thank you :D
