### ISSUE TITLE
I can import, but texture baking and material combiner do not work properly.

### ISSUE THREAD

**Issue by higeinu3594** [FlailingFog/KK-Blender-Porter-Pack#335]
The texture baker and material combiner worked for the male character, but not for the female character for some reason.
The material combiner works, but it doesn't create the result as shown in the video and I couldn't get the result I wanted.
The file selection screen does not appear for the female character and works fine for the male character.
I don't know if it is due to the fact that I had set the textures to Japanese when baking, but when importing, everything is done in English.

Blender 3.3.1 3.4
CATS 0.19
KKBP 6.2.1

![blender_MWQYxb5QNo](https://user-images.githubusercontent.com/115856191/211187796-da536e2f-0392-4528-b151-13b3ba66874b.jpg)
![blender_oczzOUGo08](https://user-images.githubusercontent.com/115856191/211187798-b8787cbf-fada-4943-b3b7-a048983bd44a.jpg)

![blender_NcNwLQcJA6](https://user-images.githubusercontent.com/115856191/211187801-2e58a76b-d74d-41a6-8ee2-14a69d4f3ea9.jpg)

**Comment by higeinu3594** [comment]
error code.
Please reply if male or female card is the problem.
Also Koikatsu Koikatsu Sunshine do you get the above error with the wrong card?
I want to run this character in UE5 so I want to solve the material and texture issue somehow.

Looking forward to your good reply.

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 439, in execute
    start_baking(folderpath, resolutionMultiplier, scene.bake_light_bool, scene.bake_dark_bool, scene.bake_norm_bool)
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 348, in start_baking
    bake_pass(resolutionMultiplier, folderpath, 'light')
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 193, in bake_pass
    getOut = raw.nodes['breaknode'].inputs[1].links[0]
IndexError: tuple index out of range


Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 439, in execute
    start_baking(folderpath, resolutionMultiplier, scene.bake_light_bool, scene.bake_dark_bool, scene.bake_norm_bool)
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 348, in start_baking
    bake_pass(resolutionMultiplier, folderpath, 'light')
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 193, in bake_pass
    getOut = raw.nodes['breaknode'].inputs[1].links[0]
IndexError: tuple index out of range



Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 439, in execute
    start_baking(folderpath, resolutionMultiplier, scene.bake_light_bool, scene.bake_dark_bool, scene.bake_norm_bool)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 348, in start_baking
    bake_pass(resolutionMultiplier, folderpath, 'light')
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\KK-Blender-Porter-Pack-621\exporting\bakematerials.py", line 193, in bake_pass
    getOut = raw.nodes['breaknode'].inputs[1].links[0]
IndexError: tuple index out of range

**Comment by FlailingFog** [comment]
Baking should work on blender 3.4 now

**Comment by higeinu3594** [comment]
Thank you for your response.

Baking worked male, female.
I will post here again if I can't find the cause of the problem and solve it a little more for the material.
