### ISSUE TITLE
Issue with applying Rigify to a specific Male card

### ISSUE THREAD

**Issue by VP1989** [FlailingFog/KK-Blender-Porter-Pack#363]
Hello. I am having some issues applying Rigify to this card. It does not seem to happen with other cards I tried so far.
![100609667_p5](https://user-images.githubusercontent.com/8047059/216108970-7b810bd8-b89b-4b5b-9448-3c64a2853845.png)

This is the log when I import the character.

```
====    KKBP Log    ====
Importing pmx files with mmdtools...
Info: Imported MMD model from "C:\Games\[ScrewThisNoise] Koikatsu BetterRepack RX14\Export_PMX\20230201180949_Bob\model.pmx"
Info: Imported MMD model from "C:\Games\[ScrewThisNoise] Koikatsu BetterRepack RX14\Export_PMX\20230201180949_Bob\Outfit 00\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 2.71s

Translating and combining shapekeys...
Warning: 1 x Draw window and swap: 100.2337 ms, average: 100.23370000 ms
Warning: 1 x Draw window and swap: 24.0831 ms, average: 24.08310000 ms
Warning: 1 x Draw window and swap: 9.8389 ms, average: 9.83890000 ms
Warning: 1 x Draw window and swap: 10.7489 ms, average: 10.74890000 ms
Warning: 1 x Draw window and swap: 15.6308 ms, average: 15.63080000 ms
Warning: 1 x Draw window and swap: 16.6218 ms, average: 16.62180000 ms
Warning: 1 x Draw window and swap: 15.3131 ms, average: 15.31310000 ms
Warning: 1 x Draw window and swap: 17.3396 ms, average: 17.33960000 ms
Warning: 1 x Draw window and swap: 15.6011 ms, average: 15.60110000 ms
Warning: 1 x Draw window and swap: 15.5724 ms, average: 15.57240000 ms
Warning: 1 x Draw window and swap: 16.0108 ms, average: 16.01080000 ms
Warning: 1 x Draw window and swap: 15.9962 ms, average: 15.99620000 ms
Warning: 1 x Draw window and swap: 16.6037 ms, average: 16.60370000 ms
Warning: 1 x Draw window and swap: 16.6078 ms, average: 16.60780000 ms
Warning: 1 x Draw window and swap: 33.6548 ms, average: 33.65480000 ms
Warning: 1 x Draw window and swap: 10.0352 ms, average: 10.03520000 ms
Warning: 1 x Draw window and swap: 11.6323 ms, average: 11.63230000 ms
Warning: 1 x Draw window and swap: 11.8870 ms, average: 11.88700000 ms
Warning: 1 x Draw window and swap: 14.0451 ms, average: 14.04510000 ms
Warning: 1 x Draw window and swap: 16.5609 ms, average: 16.56090000 ms
Warning: 1 x Draw window and swap: 18.6316 ms, average: 18.63160000 ms
Warning: 1 x Draw window and swap: 15.1594 ms, average: 15.15940000 ms
Warning: 1 x Draw window and swap: 14.5329 ms, average: 14.53290000 ms
Warning: 1 x Draw window and swap: 16.5929 ms, average: 16.59290000 ms
Warning: 1 x Draw window and swap: 24.0652 ms, average: 24.06520000 ms
Warning: 1 x Draw window and swap: 24.8502 ms, average: 24.85020000 ms
Warning: 1 x Draw window and swap: 27.3018 ms, average: 27.30180000 ms
Warning: 1 x Draw window and swap: 9.7924 ms, average: 9.79240000 ms
Warning: 1 x Draw window and swap: 9.9989 ms, average: 9.99890000 ms
Warning: 1 x Draw window and swap: 16.2992 ms, average: 16.29920000 ms
Warning: 1 x Draw window and swap: 15.0075 ms, average: 15.00750000 ms
Warning: 1 x Draw window and swap: 16.5549 ms, average: 16.55490000 ms
Warning: 1 x Draw window and swap: 15.7667 ms, average: 15.76670000 ms
Warning: 1 x Draw window and swap: 17.0969 ms, average: 17.09690000 ms
Warning: 1 x Draw window and swap: 15.4535 ms, average: 15.45350000 ms
Warning: 1 x Draw window and swap: 16.5996 ms, average: 16.59960000 ms
Warning: 1 x Draw window and swap: 18.8154 ms, average: 18.81540000 ms
Warning: 1 x Draw window and swap: 14.2111 ms, average: 14.21110000 ms
Warning: 1 x Draw window and swap: 17.1542 ms, average: 17.15420000 ms
Warning: 1 x Draw window and swap: 15.0848 ms, average: 15.08480000 ms
Warning: 1 x Draw window and swap: 15.9418 ms, average: 15.94180000 ms
Warning: 1 x Draw window and swap: 16.2836 ms, average: 16.28360000 ms
Warning: 1 x Draw window and swap: 15.9173 ms, average: 15.91730000 ms
Warning: 1 x Draw window and swap: 17.3248 ms, average: 17.32480000 ms
Warning: 1 x Draw window and swap: 15.8371 ms, average: 15.83710000 ms
Warning: 1 x Draw window and swap: 16.5177 ms, average: 16.51770000 ms
Finished in 1.65s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Warning:        Somehow found a false duplicate material but didn't merge: cf_m_tang.001
Moving duplicate material Bonelyfans in slot 20 to the original slot 1
Moving duplicate material cf_m_namida_00 in slot 9 to the original slot 8
Moving duplicate material cf_m_namida_00 in slot 10 to the original slot 8
Moving duplicate material cf_m_sirome_00 in slot 12 to the original slot 11
Info: Removed 4 slots
Warning:        Material wasn't found when separating materials: c_m_shadowcast
Warning:        Material wasn't found when separating materials: Standard
Error: Nothing selected
Warning:        Material wasn't found when separating materials: Bonelyfans.001
Info: Bonelyfans moved to Shadowcast Collection
Info: Objects moved to Hitbox Collection
Info: Removed 1183 vertice(s)
Info: Removed 17 slots
Info: Removed 15 slots
Info: Removed 5 slots
Finished in 5.29s

Categorizing bones into armature layers...
Finished in 6.50s
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots
Info: Removed 13 slots

Adding bone drivers...
Reparenting bones and setting up IKs...
Warning: 1 x Draw window and swap: 97.6221 ms, average: 97.62210000 ms
Warning: 1 x Draw window and swap: 99.8964 ms, average: 99.89640000 ms
Setting up joint bones...
Warning: 1 x Draw window and swap: 101.4211 ms, average: 101.42110000 ms
Creating eye controller and renaming bones...
Warning: 1 x Draw window and swap: 86.6458 ms, average: 86.64580000 ms
Finished in 12.5s

Applying material templates and textures...
Warning:        material or template wasn't found: Eyeline_Over / KK Eyeline Kage
Warning:        material or template wasn't found: cf_m_sirome_00 / KK Eyewhites (sirome)
Warning:        material or template wasn't found: cf_m_tooth.001 / KK Fangs (tooth.001)
Warning: 1 x Draw window and swap: 114.8550 ms, average: 114.85500000 ms
Getting textures from: C:\Games\[ScrewThisNoise] Koikatsu BetterRepack RX14\Export_PMX\20230201180949_Bob\
Warning:        Tried to create a dark version of cf_m_face_02_MT_CT.png but something went wrong. It won't be loaded in.
Warning:        Tried to create a dark version of cm_m_body_MT_CT.png but something went wrong. It won't be loaded in.
A dark version of acs_m_aviator 3430_MT_DT.png already exists
A dark version of bose 3300_MT_DT.png already exists
A dark version of bose 3330_MT_DT.png already exists
A dark version of bose 3360_MT_DT.png already exists
A dark version of bose 3390_MT_DT.png already exists
A dark version of cf_m_shoes_theif 8500_MT_DT.png already exists
Warning:        Tried to create a dark version of cm_m_dankon 7950_MT_CT.png but something went wrong. It won't be loaded in.
Warning:        Tried to create a dark version of cm_m_dan_f 7950_MT_CT.png but something went wrong. It won't be loaded in.
A dark version of inmoumat 3550_MT_DT.png already exists
A dark version of m_koi_stu_kihon01_02 3580_MT_DT.png already exists
A dark version of Tex_0007_0 3500_MT_DT.png already exists
A dark version of Tex_0007_0 3640_MT_DT.png already exists
File not found, skipping: cm_m_body_MT_DT.png
File not found, skipping: cm_m_body_CM.png
File not found, skipping: cm_m_body_MT.png
File not found, skipping: cm_m_body_T4.png
File not found, skipping: cf_m_face_02_MT_DT.png
File not found, skipping: cf_m_face_02_CM.png
File not found, skipping: cf_m_face_02_T4.png
File not found, skipping: cf_m_face_02_MT.png
File not found, skipping: cf_m_face_02_T5.png
File not found, skipping: cf_m_face_02_T6.png
File not found, skipping: cf_m_face_02_T7.png
File not found, skipping: cf_m_face_02_T8.png
File not found, skipping: cf_m_face_02_ot3.png
File not found, skipping: cf_m_noseline_00_MT_CT.png
File not found, skipping: cf_m_eyeline_kage_MT.png
File not found, skipping: Eyeline_Over_MT_CT.png
File not found, skipping: cf_m_sirome_00_cf_t_expression_00_EXPR.png
File not found, skipping: cf_m_sirome_00_cf_t_expression_01_EXPR.png
File not found, skipping: cf_m_tang_NMPD_CNV.png
File not found, skipping: bose 3300_MT.png
File not found, skipping: bose 3300_MT.png
File not found, skipping: bose 3300_CM.png
File not found, skipping: bose 3300_NMP.png
File not found, skipping: bose 3300_NMPD_CNV.png
File not found, skipping: bose 3300_AM.png
File not found, skipping: bose 3300_PM1.png
File not found, skipping: bose 3300_PM2.png
File not found, skipping: bose 3300_PM3.png
File not found, skipping: bose 3330_MT.png
File not found, skipping: bose 3330_MT.png
File not found, skipping: bose 3330_CM.png
File not found, skipping: bose 3330_NMP.png
File not found, skipping: bose 3330_NMPD_CNV.png
File not found, skipping: bose 3330_AM.png
File not found, skipping: bose 3330_PM1.png
File not found, skipping: bose 3330_PM2.png
File not found, skipping: bose 3330_PM3.png
File not found, skipping: bose 3360_MT.png
File not found, skipping: bose 3360_MT.png
File not found, skipping: bose 3360_CM.png
File not found, skipping: bose 3360_NMP.png
File not found, skipping: bose 3360_NMPD_CNV.png
File not found, skipping: bose 3360_AM.png
File not found, skipping: bose 3360_PM1.png
File not found, skipping: bose 3360_PM2.png
File not found, skipping: bose 3360_PM3.png
File not found, skipping: bose 3390_MT.png
File not found, skipping: bose 3390_MT.png
File not found, skipping: bose 3390_CM.png
File not found, skipping: bose 3390_NMP.png
File not found, skipping: bose 3390_NMPD_CNV.png
File not found, skipping: bose 3390_AM.png
File not found, skipping: bose 3390_PM1.png
File not found, skipping: bose 3390_PM2.png
File not found, skipping: bose 3390_PM3.png
File not found, skipping: Tex_0007_0 3500_MT.png
File not found, skipping: Tex_0007_0 3500_MT.png
File not found, skipping: Tex_0007_0 3500_DM.png
File not found, skipping: Tex_0007_0 3500_NMP.png
File not found, skipping: Tex_0007_0 3500_NMPD_CNV.png
File not found, skipping: Tex_0007_0 3500_AM.png
File not found, skipping: Tex_0007_0 3500_PM1.png
File not found, skipping: Tex_0007_0 3500_PM2.png
File not found, skipping: Tex_0007_0 3500_PM3.png
File not found, skipping: Tex_0007_0 3640_MT.png
File not found, skipping: Tex_0007_0 3640_MT.png
File not found, skipping: Tex_0007_0 3640_DM.png
File not found, skipping: Tex_0007_0 3640_NMP.png
File not found, skipping: Tex_0007_0 3640_NMPD_CNV.png
File not found, skipping: Tex_0007_0 3640_AM.png
File not found, skipping: Tex_0007_0 3640_PM1.png
File not found, skipping: Tex_0007_0 3640_PM2.png
File not found, skipping: Tex_0007_0 3640_PM3.png
File not found, skipping: cf_m_shoes_theif 8500_NMPD_CNV.png
File not found, skipping: cf_m_shoes_theif 8500_AM.png
File not found, skipping: cf_m_shoes_theif 8500_PM1.png
File not found, skipping: cf_m_shoes_theif 8500_PM2.png
File not found, skipping: cf_m_shoes_theif 8500_PM3.png
File not found, skipping: m_koi_stu_kihon01_02 3580_MT.png
File not found, skipping: m_koi_stu_kihon01_02 3580_MT.png
File not found, skipping: m_koi_stu_kihon01_02 3580_DM.png
File not found, skipping: m_koi_stu_kihon01_02 3580_NMPD_CNV.png
File not found, skipping: m_koi_stu_kihon01_02 3580_AM.png
File not found, skipping: m_koi_stu_kihon01_02 3580_PM1.png
File not found, skipping: m_koi_stu_kihon01_02 3580_PM2.png
File not found, skipping: m_koi_stu_kihon01_02 3580_PM3.png
File not found, skipping: inmoumat 3550_MT.png
File not found, skipping: inmoumat 3550_MT.png
File not found, skipping: inmoumat 3550_DM.png
File not found, skipping: inmoumat 3550_NMP.png
File not found, skipping: inmoumat 3550_NMPD_CNV.png
File not found, skipping: inmoumat 3550_AM.png
File not found, skipping: inmoumat 3550_PM1.png
File not found, skipping: inmoumat 3550_PM2.png
File not found, skipping: inmoumat 3550_PM3.png
File not found, skipping: cm_m_dan_f 7950.001_MT.png
File not found, skipping: cm_m_dan_f 7950.001_MT.png
File not found, skipping: cm_m_dan_f 7950.001_MT_CT.png
File not found, skipping: cm_m_dan_f 7950.001_MT_DT.png
File not found, skipping: cm_m_dan_f 7950.001_CM.png
File not found, skipping: cm_m_dan_f 7950.001_DM.png
File not found, skipping: cm_m_dan_f 7950.001_NMP.png
File not found, skipping: cm_m_dan_f 7950.001_NMPD_CNV.png
File not found, skipping: cm_m_dan_f 7950.001_AM.png
File not found, skipping: cm_m_dan_f 7950.001_PM1.png
File not found, skipping: cm_m_dan_f 7950.001_PM2.png
File not found, skipping: cm_m_dan_f 7950.001_PM3.png
File not found, skipping: cm_m_dankon 7950_MT.png
File not found, skipping: cm_m_dankon 7950_MT.png
File not found, skipping: cm_m_dankon 7950_MT_DT.png
File not found, skipping: cm_m_dankon 7950_CM.png
File not found, skipping: cm_m_dankon 7950_NMPD_CNV.png
File not found, skipping: cm_m_dankon 7950_AM.png
File not found, skipping: cm_m_dankon 7950_PM1.png
File not found, skipping: cm_m_dankon 7950_PM2.png
File not found, skipping: cm_m_dankon 7950_PM3.png
File not found, skipping: acs_m_aviator 3430_MT.png
File not found, skipping: acs_m_aviator 3430_MT.png
File not found, skipping: acs_m_aviator 3430_DM.png
File not found, skipping: acs_m_aviator 3430_NMP.png
File not found, skipping: acs_m_aviator 3430_NMPD_CNV.png
File not found, skipping: acs_m_aviator 3430_AM.png
File not found, skipping: acs_m_aviator 3430_PM1.png
File not found, skipping: acs_m_aviator 3430_PM2.png
File not found, skipping: acs_m_aviator 3430_PM3.png
File not found, skipping: acs_m_lens 3440_MT.png
File not found, skipping: acs_m_lens 3440_MT.png
File not found, skipping: acs_m_lens 3440_MT_CT.png
File not found, skipping: acs_m_lens 3440_MT_DT.png
File not found, skipping: acs_m_lens 3440_CM.png
File not found, skipping: acs_m_lens 3440_DM.png
File not found, skipping: acs_m_lens 3440_NMP.png
File not found, skipping: acs_m_lens 3440_NMPD_CNV.png
File not found, skipping: acs_m_lens 3440_AM.png
File not found, skipping: acs_m_lens 3440_PM1.png
File not found, skipping: acs_m_lens 3440_PM2.png
File not found, skipping: acs_m_lens 3440_PM3.png
File not found, skipping: m_Mask 7990_MT.png
File not found, skipping: m_Mask 7990_MT.png
File not found, skipping: m_Mask 7990_MT_CT.png
File not found, skipping: m_Mask 7990_MT_DT.png
File not found, skipping: m_Mask 7990_CM.png
File not found, skipping: m_Mask 7990_DM.png
File not found, skipping: m_Mask 7990_NMP.png
File not found, skipping: m_Mask 7990_NMPD_CNV.png
File not found, skipping: m_Mask 7990_AM.png
File not found, skipping: m_Mask 7990_PM1.png
File not found, skipping: m_Mask 7990_PM2.png
File not found, skipping: m_Mask 7990_PM3.png
File not found, skipping: cm_m_dan_f 7950_MT.png
File not found, skipping: cm_m_dan_f 7950_MT.png
File not found, skipping: cm_m_dan_f 7950_MT_DT.png
File not found, skipping: cm_m_dan_f 7950_CM.png
File not found, skipping: cm_m_dan_f 7950_NMPD_CNV.png
File not found, skipping: cm_m_dan_f 7950_AM.png
File not found, skipping: cm_m_dan_f 7950_PM1.png
File not found, skipping: cm_m_dan_f 7950_PM2.png
File not found, skipping: cm_m_dan_f 7950_PM3.png
Info: GFN Empty moved to Collection
Warning: 1 x Draw window and swap: 87.6276 ms, average: 87.62760000 ms
Adding bone widgets...
Warning: 1 x Draw window and swap: 149.7709 ms, average: 149.77090000 ms
Finished in 5.27s

Converting Colors...
C:\Games\[ScrewThisNoise] Koikatsu BetterRepack RX14\Export_PMX\20230201180949_Bob\
```

And this is what happens when I try to convert to Rigify
```
Converting to Rigify...
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 1799, in execute
    main()
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 315, in main
    arrangeTripleWidgetSet(koikatsuCommons.widgetCollectionName, widgetEyes, widgetEyeLeft, widgetEyeRight, False,
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 189, in arrangeTripleWidgetSet
    leftVertexGroupMidZ = (leftVertexGroupExtremities.maxZ + leftVertexGroupExtremities.minZ) / 2
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Error: Python: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 1799, in execute
    main()
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 315, in main
    arrangeTripleWidgetSet(koikatsuCommons.widgetCollectionName, widgetEyes, widgetEyeLeft, widgetEyeRight, False,
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 189, in arrangeTripleWidgetSet
    leftVertexGroupMidZ = (leftVertexGroupExtremities.maxZ + leftVertexGroupExtremities.minZ) / 2
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:111
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifywrapper.py", line 32, in execute
    bpy.ops.kkb.rigbefore('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 1799, in execute
    main()
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 315, in main
    arrangeTripleWidgetSet(koikatsuCommons.widgetCollectionName, widgetEyes, widgetEyeLeft, widgetEyeRight, False,
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifyscripts\rigify_before.py", line 189, in arrangeTripleWidgetSet
    leftVertexGroupMidZ = (leftVertexGroupExtremities.maxZ + leftVertexGroupExtremities.minZ) / 2
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:111
```
This is the mess I end up getting each time. What seems to be wrong here?
![image](https://user-images.githubusercontent.com/8047059/216110849-6cad0ce3-8caf-4b76-9633-4d93180fa12a.png)

**Comment by ilcane87** [comment]
Hi @VP1989, I tried the same character and got the same error, but this isn't a Rigify specific error, it's just that the model is imported without the Left Eye and Right Eye weights for some reason, dunno if it's because of the model itself or maybe some mod, but that prevents the eyes from moving even with the standard armature.

It's actually easy to fix manually though, just follow these steps without making any other changes:

1. Import the model with the 'Use KKBP Armature' option instead of the Rigify option;
2. Hide the outfit and armature, select the Body object and go into Edit Mode;
3. Zoom in on the left eye, and with Face Selection enabled, move your mouse over any of the faces inside the eye and select all of them by pressing L;
4. In the right panel, go into Object Data Properties, search for the vertex group called 'Left Eye', select it and click on Assign, as shown in the picture below:
![2023-02-02 21_57_30-Blender_  C__Users_ilcane87_Desktop_untitled blend](https://user-images.githubusercontent.com/34897042/216448993-3bf653f9-d7f0-4f13-8a5d-b6ad60ef1b45.png)
5. Then select the faces of the right eye and assign them to the 'Right Eye' vertex group;
6. Now the missing vertex groups are fixed, so go back to Object mode, un-hide the outfit and armature, select the armature and click the star-shaped 'Convert for Rigify' button, which will give you the Rigify armature with no errors and with working eyes:
![2023-02-02 21_56_10-Blender_  C__Users_ilcane87_Desktop_untitled blend](https://user-images.githubusercontent.com/34897042/216449740-a0c091d3-8e6f-4975-aa77-1da786c7a6fe.png)

I noticed that this character also doesn't have a rigged tongue, so you can delete the corresponding bones without custom shapes from their layers.

**Comment by VP1989** [comment]
@ilcane87 That card I posted is kind of an edit of the original card. In Koikatsu's character creator and KKPE, I just enabled the eyes. I will try your method and update if it worked for me.

**Comment by VP1989** [comment]
@ilcane87 OK. It works.
