### ISSUE TITLE
Baking error on linux

### ISSUE THREAD

**Issue by ghost573** [FlailingFog/KK-Blender-Porter-Pack#364]
```
Read blend: /home/metabox/Games/Koikatsu Sunshine/Export_PMX/export.blend
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elboback_L"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_kneeF_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_R"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_hand_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_leg_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_hand_L"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_siri_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_leg_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elbo_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_siri_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_L"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_shoulder02_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_siri_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elbo_L"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elboback_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elboback_R"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_siri_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elbo_R"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_kneeB_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_hand_R"].location[0]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_kneeF_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_kneeB_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_leg_L"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elboback_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_leg_L"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_kneeB_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_kneeB_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_hand_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_waist02"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_kneeF_R"].location[1]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_d_kneeF_R"].location[2]
WARN (bke.anim_sys): source/blender/blenkernel/intern/anim_sys.c:4192 BKE_animsys_eval_driver: invalid driver - pose.bones["cf_s_elbo_R"].location[2]
Switching to EEVEE for material baking...
/home/metabox/Games/Koikatsu Sunshine/Export_PMX/baked/
<bpy_struct, Object("Body") at 0x7f83e00b1c08>
ERROR (bke.modifier): source/blender/blenkernel/intern/modifier.cc:458 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): source/blender/blenkernel/intern/modifier.cc:458 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): source/blender/blenkernel/intern/modifier.cc:458 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): source/blender/blenkernel/intern/modifier.cc:458 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
Warning: 1 x Draw window and swap: 29.0082 ms, average: 29.00815010 ms
Info: Removed 2 slots

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "/home/metabox/.config/blender/3.4/scripts/addons/KK-Blender-Porter-Pack-master/exporting/bakematerials.py", line 446, in execute
    start_baking(folderpath, resolutionMultiplier, scene.bake_light_bool, scene.bake_dark_bool, scene.bake_norm_bool)
  File "/home/metabox/.config/blender/3.4/scripts/addons/KK-Blender-Porter-Pack-master/exporting/bakematerials.py", line 348, in start_baking
    bake_pass(resolutionMultiplier, folderpath, 'light')
  File "/home/metabox/.config/blender/3.4/scripts/addons/KK-Blender-Porter-Pack-master/exporting/bakematerials.py", line 216, in bake_pass
    if not currentmaterial.node_tree.nodes.get('KK Mix') and WindowsPath(folderpath + sanitizeMaterialName(currentmaterial.name) + ' ' + bake_type + '.png') in files:
  File "/home/metabox/Documents/blender/3.4/python/lib/python3.10/pathlib.py", line 962, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'WindowsPath' on your system

```

This is tested with the default character from KKS.

Did some more testing with v6.2.1 and v6.3.1 and both have this issue baking materials on linux.

**Comment by FlailingFog** [comment]
oops, does the latest commit work?

**Comment by ghost573** [comment]
Yep working good so far. Thanks so much.
