### ISSUE TITLE
Unable to pack file - 6.4.1 Create animation library

### ISSUE THREAD

**Issue by meltyblood2010** [FlailingFog/KK-Blender-Porter-Pack#380]
After following [this tutorial](https://www.youtube.com/watch?v=Ezsy6kwgBE0) on importing Koikatsu animations, I cant get past the part where you create the animation library.

It gives me this error:
Traceback (most recent call last):
  File "C:\Users\XX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\extras\animationlibrary\createanimationlibrary.py", line 389, in execute
    main(self.directory)
  File "C:\Users\XX\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\extras\animationlibrary\createanimationlibrary.py", line 170, in main
    bpy.context.scene.rsl_retargeting_armature_source = imported_armature
AttributeError: 'Scene' object has no attribute 'rsl_retargeting_armature_source'

I'm using Blender 3.4.0 and KKBP 6.4.1

**Comment by FlailingFog** [comment]
Did you install the Rokoko studio live addon?
