### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#384]
Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\exporting\exportprep.py", line 251, in execute
    main(prep_type, simp_type)
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\exporting\exportprep.py", line 47, in main
    if ob.type == 'MESH' and ob in bpy.context.view_layer.objects:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

**Comment by LegionInstaller** [comment]
Type Very Simple , No FBX Changes

**Comment by FlailingFog** [comment]
This should be fixed now
