### ISSUE TITLE
IDK this is a bug or not, but I got this error when trying to import the character in blender.

### ISSUE THREAD

**Issue by reaper242** [FlailingFog/KK-Blender-Porter-Pack#403]
Please include the Koikatsu character card that causes the issue!  

here's the card with the mods

https://drive.google.com/file/d/1L1uWKjqIRDojF6zRVKjArDseFeG7c-Bb/view?usp=sharing

You can copy paste it directly into this text box.  
(it can really help with the debug process)

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\importing\importeverything.py", line 1399, in execute
    template_error = get_templates_and_apply(directory, use_fake_user)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-641\importing\importeverything.py", line 171, in get_templates_and_apply
    body.material_slots['KK General'].material = tongue_template
KeyError: 'bpy_prop_collection[key]: key "KK General" not found'

**Comment by WeeblyMon** [comment]
have you found a solution yet?

**Comment by reaper242** [comment]
apparently not

**Comment by MoriMorinya** [comment]
Could you check if after the export finishes that the character still has their tounge in-game? it happended to me before and I think the error was the same.

Also the card link is invite only.

**Comment by reaper242** [comment]
I see, I'll try to check the character and I already change the link share to anyone with link

**Comment by reaper242** [comment]
May I know how to check if the character's tongue exist or not?

**Comment by reaper242** [comment]
Okay, So I have the character in the charastudio and check for the tongue. the character's tongue doesn't work with their own blendeshape and it's tied to the mouth expression. When I move the tongue slider , nothing happens

**Comment by MoriMorinya** [comment]
checked it and it looks more like the modded head just isn't supported in the current KKBP version
