### ISSUE TITLE
Baking not working in Blender 3.5

### ISSUE THREAD

**Issue by hdddestroyer** [FlailingFog/KK-Blender-Porter-Pack#412]
Hi, I updated Blender to 3.5 and I decided to test if the plugin works properly, but it throws a bunch of errors while baking and it doesn't progress further. Characters used don't matter.
```
<bpy_struct, Object("Body") at 0x000001E376618808>
ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\<name>\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-641\exporting\bakematerials.py", line 438, in execute
    setup_geometry_nodes_and_fillerplane(camera)
  File "C:\Users\<name>\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-641\exporting\bakematerials.py", line 155, in setup_geometry_nodes_and_fillerplane
    identifier = geonodes.node_group.inputs[1].identifier
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
ERROR (bke.modifier): C:\Users\blender\git\blender-v350\blender.git\source\blender\blenkernel\intern\modifier.cc:459 BKE_modifier_set_error: Object: "Body", Modifier: "Flattener", Node group must have an output socket
```

**Comment by FlailingFog** [comment]
Thanks, it should work in the latest commit.
