### ISSUE TITLE
6.4.1 Create animation library custom_bone_ key error

### ISSUE THREAD

**Issue by thaihoanganhquoc** [FlailingFog/KK-Blender-Porter-Pack#429]
How do i fix this ? 
I'm using Blender 3.4.0 and KKBP 6.4.1
Python: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\extras\animationlibrary\createanimationlibrary.py", line 389, in execute
    main(self.directory)
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\extras\animationlibrary\createanimationlibrary.py", line 186, in main
    bpy.ops.rsl.retarget_animation()
  File "E:\SteamLibrary\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rokoko-studio-live-blender-1-4-1\operators\retargeting.py", line 128, in execute
    custom_schemes_manager.save_retargeting_to_list()
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\rokoko-studio-live-blender-1-4-1\core\custom_schemes_manager.py", line 54, in save_retargeting_to_list
    if bone_name_target not in detection_manager.bone_detection_list_custom[bone_name_key_detected]:
KeyError: 'custom_bone_cf_d_bust00'
Location: E:\SteamLibrary\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py:113

**Comment by FlailingFog** [comment]
Try to import an animation and click the X button next to the "Custom Naming Schemes" section that appears in the Rokoko retargeting panel.
