### ISSUE TITLE
All Textures Missing on importing (Blender 3.2.2, KKBP 6.4.2, KKBP_E 4.21)

### ISSUE THREAD

**Issue by Jonah-multi** [FlailingFog/KK-Blender-Porter-Pack#437]
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/54161865/2d1e3f95-053c-41ca-b4b2-bf193f29cc63)
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/54161865/f522b8bc-1331-4659-b3ef-d7dc206246a5)

```
====    KKBP Log    ====
Importing pmx files with mmdtools...
Info: Imported MMD model from "C:\Games\LIS\Koikatsu Sunshine BetterRepack R9\Export_PMX\20230622223211_MurataHimeko\model.pmx"
Info: Imported MMD model from "C:\Games\LIS\Koikatsu Sunshine BetterRepack R9\Export_PMX\20230622223211_MurataHimeko\Outfit 04\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 2.01s

Translating and combining shapekeys...
Warning: 1 x Draw window and swap: 43.2369 ms, average: 43.23690000 ms
Warning: 1 x Draw window and swap: 19.5630 ms, average: 19.56300001 ms
Warning: 1 x Draw window and swap: 6.8353 ms, average: 6.83530001 ms
Warning: 1 x Draw window and swap: 14.8421 ms, average: 14.84209998 ms
Warning: 1 x Draw window and swap: 17.1991 ms, average: 17.19910000 ms
Warning: 1 x Draw window and swap: 15.8530 ms, average: 15.85299999 ms
Warning: 1 x Draw window and swap: 36.7324 ms, average: 36.73239995 ms
Warning: 1 x Draw window and swap: 24.6717 ms, average: 24.67169997 ms
Warning: 1 x Draw window and swap: 30.7724 ms, average: 30.77240003 ms
Warning: 1 x Draw window and swap: 21.7061 ms, average: 21.70609997 ms
Warning: 1 x Draw window and swap: 25.1953 ms, average: 25.19530000 ms
Warning: 1 x Draw window and swap: 32.2934 ms, average: 32.29340003 ms
Warning: 1 x Draw window and swap: 18.2103 ms, average: 18.21030001 ms
Warning: 1 x Draw window and swap: 30.2820 ms, average: 30.28200002 ms
Warning: 1 x Draw window and swap: 8.6984 ms, average: 8.69839999 ms
Warning: 1 x Draw window and swap: 15.9789 ms, average: 15.97889996 ms
Warning: 1 x Draw window and swap: 17.0727 ms, average: 17.07270002 ms
Warning: 1 x Draw window and swap: 15.9534 ms, average: 15.95340000 ms
Warning: 1 x Draw window and swap: 15.5588 ms, average: 15.55880002 ms
Warning: 1 x Draw window and swap: 16.5171 ms, average: 16.51709998 ms
Warning: 1 x Draw window and swap: 16.7404 ms, average: 16.74040005 ms
Warning: 1 x Draw window and swap: 15.6375 ms, average: 15.63750004 ms
Warning: 1 x Draw window and swap: 15.8658 ms, average: 15.86579997 ms
Warning: 1 x Draw window and swap: 15.5961 ms, average: 15.59610001 ms
Warning: 1 x Draw window and swap: 21.8655 ms, average: 21.86550002 ms
Warning: 1 x Draw window and swap: 21.3422 ms, average: 21.34219999 ms
Warning: 1 x Draw window and swap: 21.8645 ms, average: 21.86450001 ms
Warning: 1 x Draw window and swap: 20.2561 ms, average: 20.25609999 ms
Warning: 1 x Draw window and swap: 7.3431 ms, average: 7.34310003 ms
Warning: 1 x Draw window and swap: 9.7752 ms, average: 9.77519999 ms
Warning: 1 x Draw window and swap: 17.4296 ms, average: 17.42960000 ms
Warning: 1 x Draw window and swap: 15.5587 ms, average: 15.55869996 ms
Warning: 1 x Draw window and swap: 16.2441 ms, average: 16.24410000 ms
Warning: 1 x Draw window and swap: 16.1978 ms, average: 16.19780000 ms
Warning: 1 x Draw window and swap: 16.2253 ms, average: 16.22529997 ms
Warning: 1 x Draw window and swap: 15.7995 ms, average: 15.79949999 ms
Warning: 1 x Draw window and swap: 15.4884 ms, average: 15.48840001 ms
Warning: 1 x Draw window and swap: 15.6644 ms, average: 15.66440001 ms
Warning: 1 x Draw window and swap: 16.6976 ms, average: 16.69760002 ms
Warning: 1 x Draw window and swap: 15.8077 ms, average: 15.80769999 ms
Warning: 1 x Draw window and swap: 16.3898 ms, average: 16.38980000 ms
Warning: 1 x Draw window and swap: 15.9474 ms, average: 15.94739995 ms
Warning: 1 x Draw window and swap: 16.9078 ms, average: 16.90780005 ms
Warning: 1 x Draw window and swap: 15.7289 ms, average: 15.72890003 ms
Warning: 1 x Draw window and swap: 15.8487 ms, average: 15.84870002 ms
Warning: 1 x Draw window and swap: 16.2793 ms, average: 16.27929998 ms
Finished in 1.42s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Info: Removed 44 slots
Info: Removed 44 slots
Info: Removed 42 slots
Info: Removed 7 slots
Moving duplicate material Bonelyfans in slot 14 to the original slot 1
Moving duplicate material cf_m_sirome_00 in slot 9 to the original slot 8
Info: Removed 2 slots
Moving duplicate material empty 474 in slot 1 to the original slot 0
Moving duplicate material empty 984 in slot 3 to the original slot 2
Moving duplicate material empty 2444 in slot 9 to the original slot 8
Moving duplicate material empty 2654 in slot 11 to the original slot 10
Moving duplicate material empty 2654 in slot 12 to the original slot 10
Moving duplicate material empty 2654 in slot 13 to the original slot 10
Moving duplicate material ee 3784 in slot 15 to the original slot 14
Moving duplicate material empty 5354 in slot 19 to the original slot 18
Moving duplicate material empty 5674 in slot 26 to the original slot 25
Moving duplicate material empty 5954 in slot 30 to the original slot 29
Moving duplicate material empty 5954 in slot 31 to the original slot 29
Moving duplicate material empty 7594 in slot 33 to the original slot 32
Moving duplicate material empty 8294 in slot 37 to the original slot 36
Moving duplicate material empty 8894 in slot 40 to the original slot 39
Moving duplicate material empty 8954 in slot 42 to the original slot 41
Info: Removed 15 slots

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 295, in separate_everything
    if bpy.data.objects['Outfit 00'].material_slots.get('cf_O_face_atari_M.001'):
KeyError: 'bpy_prop_collection[key]: key "Outfit 00" not found'

Error: Traceback (most recent call last):
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 295, in separate_everything
    if bpy.data.objects['Outfit 00'].material_slots.get('cf_O_face_atari_M.001'):
KeyError: 'bpy_prop_collection[key]: key "Outfit 00" not found'

Traceback (most recent call last):
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\importbuttons.py", line 93, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 700, in execute
    separate_everything(context)
  File "C:\Users\capta\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\KK-Blender-Porter-Pack-642\importing\separatebody.py", line 295, in separate_everything
    if bpy.data.objects['Outfit 00'].material_slots.get('cf_O_face_atari_M.001'):
KeyError: 'bpy_prop_collection[key]: key "Outfit 00" not found'
```

**Comment by Jonah-multi** [comment]
OKAY, so as it turns out. If you export a single outfit, butt it isn't outfit 00, it causes the system to crash.

**Comment by 777Leinad77** [comment]
> OKAY, so as it turns out. If you export a single outfit, but it isn't outfit 00, it causes the system to crash.

Same issue with me , it worked  for  me when i renamed the folder "Outfit 05" into "Outfit 00", in the folder Export_PMX/[folder of the converted card]

**Comment by FlailingFog** [comment]
Exporting a single outfit that isn't Outfit 00 seems to now work on 6.6.0
