### ISSUE TITLE
import model issue

### ISSUE THREAD

**Issue by HaiseSaeye** [FlailingFog/KK-Blender-Porter-Pack#452]
card and mod

https://drive.google.com/drive/folders/1Jj4pQB57EjvKqgEy9RvfvYtGrUxnK7yW?usp=sharing

Importing pmx files with mmdtools...
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230726231451_ChikaHaruno\model.pmx"
Info: Imported MMD model from "E:\KK\Koikatsu.Party\Koikatsu.Party\Koikatsu Party After Party\Export_PMX\20230726231451_ChikaHaruno\Outfit 00\model.pmx"

Finalizing PMX file...
Modifying armature...
Finished in 6.06s

Translating and combining shapekeys...
Warning: 1 x Draw window and swap: 81.5818 ms, average: 81.58180000 ms
Warning: 1 x Draw window and swap: 11.8150 ms, average: 11.81500000 ms
Warning: 1 x Draw window and swap: 25.0004 ms, average: 25.00040000 ms
Warning: 1 x Draw window and swap: 38.8871 ms, average: 38.88710000 ms
Warning: 1 x Draw window and swap: 15.7309 ms, average: 15.73090000 ms
Warning: 1 x Draw window and swap: 25.6596 ms, average: 25.65960000 ms
Warning: 1 x Draw window and swap: 24.7155 ms, average: 24.71550000 ms
Warning: 1 x Draw window and swap: 24.6767 ms, average: 24.67670000 ms
Warning: 1 x Draw window and swap: 12.2372 ms, average: 12.23720000 ms
Finished in 0.54s

Separating body, clothes, hair, hitboxes and shadowcast, then removing duplicate materials...
Warning:        Material wasn't found when separating materials:
Error: Nothing selected

Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 697, in execute
    make_tear_and_gag_shapekeys()
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 466, in make_tear_and_gag_shapekeys
    separate_materials(body, tearMats)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Error: Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 697, in execute
    make_tear_and_gag_shapekeys()
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 466, in make_tear_and_gag_shapekeys
    separate_materials(body, tearMats)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\importbuttons.py", line 93, in execute
    bpy.ops.kkb.separatebody('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 697, in execute
    make_tear_and_gag_shapekeys()
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 466, in make_tear_and_gag_shapekeys
    separate_materials(body, tearMats)
  File "C:\Users\haise\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\KK-Blender-Porter-Pack-650\importing\separatebody.py", line 145, in separate_materials
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected

**Comment by DiegoBotto2004** [comment]
I have the same problem, I´m trying to import the model in blender 3.4 and I have this error:
Python: Traceback (most recent call last):
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\importing\importbuttons.py", line 95, in execute
    bpy.ops.kkb.bonedrivers('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\importing\bonedrivers.py", line 845, in execute
    setup_iks()
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\importing\bonedrivers.py", line 115, in setup_iks
    legIK('cf_j_leg01_R', 'cf_pv_foot_R', 'cf_pv_knee_R', math.pi/2, 'cf_pv_foot_R', 'cf_j_leg01_R', 'cf_j_toes_R', 'cf_j_foot_R')
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-642\importing\bonedrivers.py", line 87, in legIK
    bone.constraints["IK"].target = bpy.data.objects['Armature']
KeyError: 'bpy_prop_collection[key]: key "IK" not found'
