### ISSUE TITLE
I can't import the model with KKBP Armature

### ISSUE THREAD

**Issue by DiegoBotto2004** [FlailingFog/KK-Blender-Porter-Pack#463]
https://drive.google.com/drive/folders/1KhN0gCYY8qvHujtpAYkEGOJj4sgTYsEL
I'm trying to import the model in Blender 3.4 with KKBP Armature but I can't, I get this error:
Python: Traceback (most recent call last):
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 109, in execute
    bpy.ops.kkb.bonedrivers('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\importing\bonedrivers.py", line 846, in execute
    setup_iks()
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\importing\bonedrivers.py", line 115, in setup_iks
    legIK('cf_j_leg01_R', 'cf_pv_foot_R', 'cf_pv_knee_R', math.pi/2, 'cf_pv_foot_R', 'cf_j_leg01_R', 'cf_j_toes_R', 'cf_j_foot_R')
  File "C:\Users\Diego Botto\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\KK-Blender-Porter-Pack-master\importing\bonedrivers.py", line 87, in legIK
    bone.constraints["IK"].target = bpy.data.objects['Armature']
KeyError: 'bpy_prop_collection[key]: key "IK" not found'
How can I fix that error?

**Comment by germantrino** [comment]
Tengo el mismo error y usé usé blender 3.5.1, KKBP 6.5.0 y HF. Sino tocará hacer el texturizado a mano 😆
