### ISSUE TITLE
Can't convert the rig to Rigify and can't separate eyes and eyebrows

### ISSUE THREAD

**Issue by hdddestroyer** [FlailingFog/KK-Blender-Porter-Pack#469]
The card doesn't seem to be important here as I tried it with 2 characters so far with same results. But here is one of them just in case: https://db.bepis.moe/koikatsu/view/308555

Error with Rigify:
`Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\extras\rigifywrapper.py", line 16, in execute
    p = post_operations()
TypeError: bpy_struct.__new__(type): expected a single argument
`

Error when trying to separate the eyes and eyebrows through addon:

`Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\extras\linkshapekeys.py", line 79, in execute
    separateMaterial(eye_list)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\extras\linkshapekeys.py", line 76, in separateMaterial
    bpy.ops.mesh.separate(type='SELECTED')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Nothing selected
`

Both of these on 6.6.0.
Rigify worked fine on previous version.

**Comment by NaughtDZ** [comment]
me too,have same error with rigify

**Comment by ilcane87** [comment]
About the Rigify issue, given the type of error it's probably just an oversight.
Until it gets fixed, I just tested that you can get the Rigify armature if you select it as option in the top menu when importing a new model.

**Comment by FlailingFog** [comment]
Thanks, both buttons should work now. 
Like ilcane87 said you can also automatically use Rigify during import by changing the armature option in the panel
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/65811931/ef66f051-c917-426a-bb1f-de5cd938724c)
