### ISSUE TITLE
Issue with Importing to blender 3.6

### ISSUE THREAD

**Issue by Zero-One-Dawn** [FlailingFog/KK-Blender-Porter-Pack#476]
`Error:          Unknown python error occurred.
          Make sure the default model imports correctly before troubleshooting on this model!
Traceback (most recent call last):
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 1603, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment`

`Error: Traceback (most recent call last):
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 1603, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment`

`Traceback (most recent call last):
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\importbuttons.py", line 85, in execute
    function()
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\importbuttons.py", line 62, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\jgeff\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V660\importing\modifymaterial.py", line 1603, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment`
this happens with the default model, and it happens with [the card i was trying to export](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/12780126/kks.card.zip)

**Comment by FlailingFog** [comment]
I think this error is now fixed in the latest version (6.6.2)
