### ISSUE TITLE
import using rigify or pmx armature issue

### ISSUE THREAD

**Issue by maidemao** [FlailingFog/KK-Blender-Porter-Pack#493]
I have issue importing character using rigify or pmx armature.  I got the following errors and armature didn't get convert to the selected type.
Updated to the latest version on both the porter pack and exporter and it didn't help.

Error:          Unknown python error occurred.
          Make sure the default model imports correctly before troubleshooting on this model!

Traceback (most recent call last):

  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 1604, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment

Error: Traceback (most recent call last):
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 1604, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment

Traceback (most recent call last):
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\importbuttons.py", line 85, in execute
    function()
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\importbuttons.py", line 70, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 73, in execute
    self.load_json_colors()
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 993, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
  File "C:\Users\maidemao\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\importing\modifymaterial.py", line 1604, in update_shaders
    shadow_color}
UnboundLocalError: local variable 'shadow_color' referenced before assignment

![BR-Chan KKS](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/38384757/e0e1d914-41d3-4a2d-b3d1-a9dd315912eb)

**Comment by FlailingFog** [comment]
this should be fixed in kkbp 7.0.0
