### ISSUE TITLE
Can't import anything with any version.

### ISSUE THREAD

**Issue by Crlat** [FlailingFog/KK-Blender-Porter-Pack#496]
It has been a while since i could use this tool but now, It's been a constant error wall whenever I want to import any model.

Error :

Importing pmx files with mmdtools...
ERROR:ActionRecorder:69:Uncaught exception
TypeError: Converting a Python list to an RNA collection: keyword "type" missing
ERROR:ActionRecorder:69:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 82, in execute
    self.import_pmx_models()
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 105, in import_pmx_models
    bpy.ops.mmd_tools.import_model('EXEC_DEFAULT',
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  MMD_TOOLS_OT_import_model.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 82, in execute
    self.import_pmx_models()
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 105, in import_pmx_models
    bpy.ops.mmd_tools.import_model('EXEC_DEFAULT',
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  MMD_TOOLS_OT_import_model.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

ERROR:ActionRecorder:69:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 82, in execute
    self.import_pmx_models()
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 105, in import_pmx_models
    bpy.ops.mmd_tools.import_model('EXEC_DEFAULT',
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  MMD_TOOLS_OT_import_model.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

Card :

(Froot(Metal) by vsjkkanon)

**Comment by DiegoBotto2004** [comment]
Same problem in this tool.

**Comment by FlailingFog** [comment]
This looks more like an error with ActionRecorder or mmd_tools. Can you try disabling ActionRecorder, or try installing the latest mmd_tools?

**Comment by DiegoBotto2004** [comment]
Where we can disable ActionRecorder in Blender?

**Comment by Crlat** [comment]
After disabling AR, same problem but without the AR notice. It can delete the cube, the light and even add an empty but that's all.

Error :

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 82, in execute
    self.import_pmx_models()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\importbuttons.py", line 105, in import_pmx_models
    bpy.ops.mmd_tools.import_model('EXEC_DEFAULT',
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  MMD_TOOLS_OT_import_model.files error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing

INFO:charset_normalizer:127:Using lazy str decoding because the payload is quite large, (10737418240) byte(s).
INFO:charset_normalizer:353:ascii was excluded because of initial chaos probing. Gave up 2 time(s). Computed mean chaos is 800.000000 %.
INFO:charset_normalizer:353:utf_8 was excluded because of initial chaos probing. Gave up 2 time(s). Computed mean chaos is 800.000000 %.

but if I wait a bit, blender goes on using 100% of my ram(32gb) and freeze.
