### ISSUE TITLE
Exporting / preping for target app fails

### ISSUE THREAD

**Issue by RedCorpDE** [FlailingFog/KK-Blender-Porter-Pack#512]
Hey there I'm trying to export a couple of characters,
but I always get  this issue while exporting:

`Error:          Unknown python error occurred
Traceback (most recent call last):
  File "C:\Users\Redsh\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\exporting\exportprep.py", line 259, in execute
    main(prep_type, simp_type)
  File "C:\Users\Redsh\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-V662\exporting\exportprep.py", line 125, in main
    armature.data.edit_bones['Left leg'].parent = armature.data.edit_bones['Hips']
KeyError: 'bpy_prop_collection[key]: key "Left leg" not found'`

Is there a fix for this?
Anything I'm doing wrong?
Thanks in advance!

Blender Version 3.6.2
CATS is installed
KKBP V6.6.2

**Comment by An12854** [comment]
It happened to me too but instead it's

`exportprep.py", line 121, in main
    armature.data.edit_bones['Pelvis'].parent = None
KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found'`

I'm using Blender 3.6.7 with the most recent version of the KKBP tools

**Comment by An12854** [comment]
@RedCorpDE Try exporting it without a custom pose, it works for me without doing it
