### ISSUE TITLE
not converting to rigify 

### ISSUE THREAD

**Issue by Jersey62** [FlailingFog/KK-Blender-Porter-Pack#536]
Hello so i was gonna convert a model to be used with Rigify and i got this error while trying to do it 
Traceback (most recent call last):
  File "C:\Users\ts051\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\extras\rigifywrapper.py", line 18, in execute
    post_operations.apply_rigify()
  File "C:\Users\ts051\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\KK-Blender-Porter-Pack-master\importing\postoperations.py", line 291, in apply_rigify
    c.switch(self.armature, 'object')
AttributeError: type object 'post_operations' has no attribute 'armature'

**Comment by videoman614** [comment]
Did you enable the Rigify addon?

**Comment by Jersey62** [comment]
> Did you enable the Rigify addon?

yes

**Comment by Erwin11** [comment]
I had same situation with u. but it works after switch to kk version by BeterRepack RX20. maybe it cause HF patch.  try on another KK version
