### ISSUE TITLE
Error on specific card

### ISSUE THREAD

**Issue by S00pergang** [FlailingFog/KK-Blender-Porter-Pack#558]
- Koikatsu Sunshine ver : 1.4.1
- HF Patch ver : 1.16
- Blender ver :  3.6.9
- KKBP_Exporter ver : 4.30
- KK Blender Porter ver : 6.6.2
- MMD Tools ver : 2.9.2

_I'd like to post the card causing it, but I'm anxious of having cards stolen. So if I can DM you it later somehow somewhere that'd be great_

```Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\addons\KK-Blender-Porter-Pack-663\importing\importbuttons.py", line 85, in execute
    function()
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\addons\KK-Blender-Porter-Pack-663\importing\importbuttons.py", line 60, in <lambda>
    lambda:bpy.ops.kkbp.modifymesh('INVOKE_DEFAULT'),
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\addons\KK-Blender-Porter-Pack-663\importing\modifymesh.py", line 38, in execute
    self.separate_alternate_clothing()
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\addons\KK-Blender-Porter-Pack-663\importing\modifymesh.py", line 160, in separate_alternate_clothing
    ref_data = c.get_json_file('KK_ReferenceInfoData.json')
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\scripts\addons\KK-Blender-Porter-Pack-663\common.py", line 41, in get_json_file
    json_data = json.load(json_file)
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\blender-3.6.9-windows-x64\3.6\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by S00pergang** [comment]
### actually, after running more tests, I believe it has to do with these following accessories
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/112852330/b1926340-0dde-47da-9a89-7db3718b966e)


### BTW it seems when I successfully import (using the default chara I exported) The hair, clothes and body are messed up, body is invisible, hair is white with a yellow gradient and clothes are also blank.
![image](https://github.com/FlailingFog/KK-Blender-Porter-Pack/assets/112852330/20de1958-3962-4903-9640-a6a08a7140e6)
