### ISSUE TITLE
KKBP importer "list index out of range" not completing male import

### ISSUE THREAD

**Issue by prime15n16** [FlailingFog/KK-Blender-Porter-Pack#592]
Trying to import this male, but it isn't finalizing and allowing me to import animations, it worked for my female character. I'm using KKBP 7.0.0 in Blender 4.2, with 3.6.9 as the older dependency, as well as the Koikatsu Sunshine Better Repack updated to include the T-Pose.

![KoikatsuSun_M_20240609200349950_Connor Mason_prime15](https://github.com/user-attachments/assets/cd05c5c5-1039-4d96-b5ba-abe916a4275b)

Error:          Unknown python error occurred.
          Make sure the default model imports correctly before troubleshooting on this model!

Traceback (most recent call last):
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 74, in execute
    self.load_json_colors()
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1020, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1471, in update_shaders
    shader_inputs['Skin color'].default_value = body_colors[0] if light else body_colors[5]
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range

Error: Traceback (most recent call last):
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 74, in execute
    self.load_json_colors()
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1020, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1471, in update_shaders
    shader_inputs['Skin color'].default_value = body_colors[0] if light else body_colors[5]
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range

Traceback (most recent call last):
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 97, in execute
    function()
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 71, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 74, in execute
    self.load_json_colors()
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1020, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prime\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 1471, in update_shaders
    shader_inputs['Skin color'].default_value = body_colors[0] if light else body_colors[5]
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by prime15n16** [comment]
the import single animations and create animation library buttons are also faded out and don't work

**Comment by FlailingFog** [comment]
The animation buttons will only work if you import with the KKBP rigify armature and have the rokoko studio live addon installed. And I'm not sure why it isn't working because that card imports correctly for me. 

Could you make sure you're using the KKBP_exporter.dll from this release? 
https://github.com/FlailingFog/KK-Blender-Porter-Pack/releases/tag/V7.0.0_release_preview

**Comment by prime15n16** [comment]
Whack, I'm sure I have the right version of the exporter cuz it worked with a female card, Rokoko and rigify are enabled too. I'm gonna try redownloading the exporter and go from there

**Comment by prime15n16** [comment]
Welp, after trying that, it works! I don't know what was wrong with my initial character exports, but redownloading the KKBP exporter worked, and it ran the rigify script!
