### ISSUE TITLE
Cannot import character into Blender KKBP 7.0.0

### ISSUE THREAD

**Issue by Eidenz** [FlailingFog/KK-Blender-Porter-Pack#602]
Hello, when try to import the character I get the following error after a while:
```
Traceback (most recent call last):
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 52, in execute
    self.replace_materials_for_body()
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 236, in replace_materials_for_body
    swap_body_material([self.body['SMR materials']['cf_O_tooth'][0] + '.001'],'KK Fangs (tooth.001)')
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties

Error: Traceback (most recent call last):
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 52, in execute
    self.replace_materials_for_body()
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 236, in replace_materials_for_body
    swap_body_material([self.body['SMR materials']['cf_O_tooth'][0] + '.001'],'KK Fangs (tooth.001)')
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties

Traceback (most recent call last):
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 112, in execute
    function()
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 86, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 52, in execute
    self.replace_materials_for_body()
  File "C:\Users\eiden\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 236, in replace_materials_for_body
    swap_body_material([self.body['SMR materials']['cf_O_tooth'][0] + '.001'],'KK Fangs (tooth.001)')
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties
```

Problem is my character is an asset I'm not allowed to share, so hopefully the traceback is enough?

Running Blender 4.2.1 LTS.

**Comment by FlailingFog** [comment]
I think you're running into the same issue as https://github.com/FlailingFog/KK-Blender-Porter-Pack/issues/618, where your headmod is missing one of the face materials, so I'm going to close this one in favor of that one. I added the checks mentions in #618, so if you want to try it again in KKBP 7.1.0 it might import correctly, but if not then I need to add more checks
