### ISSUE TITLE
Problem with Converting and applying shaders (Blender 3.0.0)

### ISSUE THREAD

**Issue by Kuuuro** [FlailingFog/KK-Blender-Porter-Pack#619]
Blender 3.0.0
KKBP 5.1.0
CATS 0.19.0

Issue happening at 2b), i removed KKUTS too, thinking it could come from this.

Python: Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 726, in execute
    load_luts(lut_light, lut_dark)
  File "D:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing\importcolors.py", line 456, in load_luts
    day_lut.save()
RuntimeError: Error: Image 'Lut_TimeDay.png' could not be saved to 'D:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\KK-Blender-Porter-Pack-master\importing/luts/Lut_TimeDay.png'

location: <unknown location>:-1

I saw that the issue is not supposed to happens at this version so i'm a bit lost ngl.

**Comment by FlailingFog** [comment]
Wow, 5.1.0 was from a while ago... Is something preventing you from using a newer version of the plugins?

From the error message, maybe you don't have write access to that directory? Try running blender as admin or try running blender from the portable version instead.

**Comment by Kuuuro** [comment]
Welp, look like it was that, how did you know ? 

Btw is there a shapekey or something to like, open vagina or something ? Or do i have to add it ?

Sorry for the time, and for answering your question, i use this version because i need blender 3.0 to importing model on Virt-A-Mate

**Comment by FlailingFog** [comment]
Cool!

> Btw is there a shapekey or something to like

I don't remember for that version to be honest. I know at some point you had to choose one of the "Better Penetration" body types in Koikatsu before you exported the card or those bones wouldn't be available. And when they were available you had to enable one of the armature layers in the armature properties to get them to show up
https://docs.blender.org/manual/en/3.5/animation/armatures/properties/skeleton.html#bpy-types-armature-layers

There's no simple shapekey for that though, it's all bones and there are like 8 or 10 bones (which is more flexible than a shapekey I guess, but takes more time to setup)
