### ISSUE TITLE
Support for Evaan Cards

### ISSUE THREAD

**Issue by BlenderFan24** [FlailingFog/KK-Blender-Porter-Pack#623]
![Koikatu_F_20230606132628615_Nami_Evaan](https://github.com/user-attachments/assets/8b53baaa-73d0-4635-a8b6-d4eab4320ca6)
![Koikatu_F_20230214204842716_Robin Nico_Evaan](https://github.com/user-attachments/assets/ddbe5d52-ea20-4edd-8199-a3cb841a304c)
![Koikatu_F_20231003025423115_Hancock Boa_Evaan](https://github.com/user-attachments/assets/869db1ac-dec8-4209-bfd0-d822846f1462)

Blender 3.6.9 lts
KK Blender Porter pack 6.6.3
mmd_tools 2.9.2
and the corresponding exporting dll for koikatsu.
Koikatsu Better repack 21 (I already exported characters from here with sucess)

Hello again awesome FlailingFog and Team, this time i wanted ask if it is possible to add support to this awesome addon to make most models of Evaan (a known modder of Koikatsu) load with textures. 

Aparently the models that don't use "cf_m_tooth_MT_CT" like this ones won't load with textures showing the following errors on the console

Traceback (most recent call last):
  File "......\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 51, in execute
    if 'cf_O_tooth' in self.body['SMR materials']:
  File "........\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 233, in replace_materials_for_body
    c.import_from_library_file(category='Material', list_of_items=templateList, use_fake_user=True)
TypeError: only strings are allowed as keys of ID properties

Error: Traceback (most recent call last):
  File ".......\blender-3.6.9-windows-x64\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 51, in execute
    if 'cf_O_tooth' in self.body['SMR materials']:
  File ".....\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 233, in replace_materials_for_body
    c.import_from_library_file(category='Material', list_of_items=templateList, use_fake_user=True)
TypeError: only strings are allowed as keys of ID properties

Traceback (most recent call last):
  File ".....\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\importbuttons.py", line 85, in execute
    function()
  File ".......\blender-3.6.9-windows-x64\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\importbuttons.py", line 70, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
  File ".........\blender-3.6.9-windows-x64\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "..........\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 51, in execute
    if 'cf_O_tooth' in self.body['SMR materials']:
  File ".........\blender-3.6.9-windows-x64\3.6\scripts\addons\1 KK-Blender-Porter-Pack-663\importing\modifymaterial.py", line 233, in replace_materials_for_body
    c.import_from_library_file(category='Material', list_of_items=templateList, use_fake_user=True)
TypeError: only strings are allowed as keys of ID properties

"i have looked tooth like textures called "cf_m_mouthinside_MT_CT" which were baked with other textures of the mouth too. How can i load those models. Please make a guide or add a support to load this awesome models from Evaan, or a guide will be great to maybe modify the support for the customized materials please, i beg you, i really love this addon, and i would be awesome if you could make it compatible with Blender 3.6.9. thanks in advance-

**Comment by DiegoBotto2004** [comment]
The same here, I wanted to export from evaan cards but I get similar or the same errors.

**Comment by BlenderFan24** [comment]
Really? not even a small hint to solve this situation? maybe fix it with SB3Utility modifying the materials name? or modifications in the KK_SMRData.json? i have read a lot of the posts to try to understand how to fix this but is confusing or not enough documented. In the last 8.0 alpha build of this awesome addon it does import the model with most of the textures but the head (at least on the model im trying to do) but i don't understand at all how to "manually" fix the problem. If you import those models even on the last 8.0 version of the addon the "Finalize Materials" or "Prepare for Application" are greyed out which make it impossible to fix the model even adding the textures manually. I have tried to export the FBX from Blender 4+ and it seems to manage things diferently. if you try to export the model it won't export with the vertex groups (weights), so how it is possble to manually fix those head mods?
