### ISSUE TITLE
ZeroDivisionError: float division by zero while importing.

### ISSUE THREAD

**Issue by Atuocorrect** [FlailingFog/KK-Blender-Porter-Pack#635]
Koikatsu character card that causes the issue:
![Koikatu_F_20240928182504844_Glum Anraki-san](https://github.com/user-attachments/assets/4e3f2983-c3ae-4f74-89f3-e4718529a1ed)

Error thingy:
Error:          Unknown python error occurred. 
          Make sure the default model imports correctly before troubleshooting on this model!

Traceback (most recent call last):
  File "C:\Users\gacha\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 59, in execute
    self.link_textures_for_body()
  File "C:\Users\gacha\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 548, in link_textures_for_body
    bpy.data.node_groups['Eye Textures positioning'].nodes['eye_scale'].inputs[1].default_value = 1/float(face_data[18]['Value'])
                                                                                                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

the default female works and so does other models i've imported.
blender 4.2.2 LTS KKBP importer:7.1.0 exporter:4.30 Koikatsu: BetterRepackRX21.
this may just be an 'i don't understand blender and stuff' issue. :)

**Comment by Atuocorrect** [comment]
I have now figured out it was because the iris height and width were at 0 rather than 1 and that was causing the problem, although now when the eyes load in they are entirely white.
