### ISSUE TITLE
Detailed Cheekbones + Lips headmods break on saturation step 

### ISSUE THREAD

**Issue by MoriMorinya** [FlailingFog/KK-Blender-Porter-Pack#639]
Basically anyone of these headmods throw a numpy error when imported into blender
![image](https://github.com/user-attachments/assets/a2112e95-cfea-42d2-aba8-01a4fcc8efbe)

```
Error: Traceback (most recent call last):
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 72, in execute
    self.load_json_colors()
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 1061, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 1601, in update_shaders
    shader_inputs['Eyeline shadow color'].default_value = self.saturate_color(kage_color, active_lut)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importiTraceback (most recent call last):
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\importbuttons.py", line 108, in execute
    function()
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\importbuttons.py", line 85, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\BLENDER VERSIONS\stable\blender-4.3.0-stable.2b18cad88b13\4.3\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Traceback (most recent call last):
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 72, in execute
    self.load_json_colors()
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 1061, in load_json_colors
    self.update_shaders(json_color_data, self.lut_selection, self.lut_light, light = True) # Set light colors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 1601, in update_shaders
    shader_inputs['Eyeline shadow color'].default_value = self.saturate_color(kage_color, active_lut)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\kkbp\importing\modifymaterial.py", line 1123, in saturate_color
    image_pixels = numpy.array(color).reshape(height, width, 4)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 5 into shape (1,1,4)
```

**Comment by VickyFrenzy** [comment]
Hey can you try my fork and tell me if it fixes your issue? I might make a PR but I want to be sure what I've done does help
https://github.com/VickyFrenzy/KK-Blender-Porter-Pack/tree/dehya-dirty-fix

**Comment by MoriMorinya** [comment]
Yep it works now
