### ISSUE TITLE
Blender 4.2 modifymaterial / importbuttons error

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Porter-Pack#654]
remove_unused_material_slots operation took 0.038 seconds

Error:          Unknown python error occurred.
          Make sure the default model imports correctly before troubleshooting on this model!

Traceback (most recent call last):
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 49, in execute
    self.remap_duplcate_material_slots()
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 150, in remap_duplcate_material_slots
    if material_list.get(base_name) and int(dupe_number) and 'cf_m_hitomi_00' not in base_name and self.body['SMR materials']['o_tang'][0] not in base_name:
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties

Error: Traceback (most recent call last):
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 49, in execute
    self.remap_duplcate_material_slots()
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 150, in remap_duplcate_material_slots
    if material_list.get(base_name) and int(dupe_number) and 'cf_m_hitomi_00' not in base_name and self.body['SMR materials']['o_tang'][0] not in base_name:
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties

Traceback (most recent call last):
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 108, in execute
    function()
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\importbuttons.py", line 85, in <lambda>
    lambda:bpy.ops.kkbp.modifymaterial('INVOKE_DEFAULT'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 107, in __call__
    ret = _op_call(self.idname_py(), kw, C_exec, C_undo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 49, in execute
    self.remap_duplcate_material_slots()
  File "C:\Users\<USERNAME>\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\kkbp\importing\modifymaterial.py", line 150, in remap_duplcate_material_slots
    if material_list.get(base_name) and int(dupe_number) and 'cf_m_hitomi_00' not in base_name and self.body['SMR materials']['o_tang'][0] not in base_name:
                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: only strings are allowed as keys of ID properties


Since it's a patreon card I am unable to share the card (unless very much needed)

**Comment by LegionInstaller** [comment]
Great :/

**Comment by FlailingFog** [comment]
I’m sorry, I have come to the determination that I do not want to support any head mods. This looked like a head mod issue so I closed it. If you find that it's not a head mod issue please feel free to reopen it

**Comment by LegionInstaller** [comment]
> I’m sorry, I have come to the determination that I do not want to support any head mods. This looked like a head mod issue so I closed it. If you find that it's not a head mod issue please feel free to reopen it

Quoting from the latest release: The plugin expected all body materials to be present, but some headmods either remove or rename these materials, causing errors. Now it will skip some materials if they don't exist, allowing the headmod to at least import so you can fix it manually

How would I fix it manually ?

**Comment by LegionInstaller** [comment]
> > How would I fix it manually ?
> 
> The way it was supposed to work was that the plug-in would see an unknown body material like cf_m_Miyabi_face_00 and skip over it so you wouldn't get any errors during the import process. Then once the import was finished, you were supposed to be able to create the material yourself and set it up using the textures from the PMX folder. It looks like this didn't completely work out because you got an error, even with these changes in place.
> 
> The only suggestion I have at the moment is to find what the base game head material names are and make the head mod material names match. Some head mods also lack materials that the base game head has, so if any of those are missing, it'll likely cause problems. You might want to specifically check if the tongue material is missing or renamed on that head mod because that's what the error is about

It's alright , I've already given up, I don't really know where to begin searching or fixing nor do I really understand the error itself
