### ISSUE TITLE
Preserve small bones.

### ISSUE THREAD

**Issue by BugMonkey42335** [FlailingFog/KK-Blender-Porter-Pack#74]
While attempting to import this arachne card, I recive the following error.

> Python: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\finalizepmx.py", line 907, in execute
    bpy.ops.kkb.cleanarmature('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\cleanarmature.py", line 318, in execute
    reorganize_armature_layers()
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\cleanarmature.py", line 169, in reorganize_armature_layers
    set_armature_layer(bone, show_layer = 0)
  File "C:\Users\Standard\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Porter-Pack-master\importing\cleanarmature.py", line 124, in set_armature_layer
    bpy.data.armatures[0].bones[bone_name].layers = (
KeyError: 'bpy_prop_collection[key]: key "cf_j_foot_L" not found'
>
> location: C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py:130
>
>
>
> location: <unknown location>:-1

![Koikatu_F_20190616052416968](https://user-images.githubusercontent.com/64150986/143616299-66f11c2b-809c-4cb3-9132-bac9885858f3.png)

**Comment by BugMonkey42335** [comment]
So doing some testing I have found what is causing the issues with the Make Knight card.
It seems that the names of certain materials are preventing the scripts from working.
When I renamed the materials before running the scripts everthing ran smoothly.

- Renaming the sword's material and files from **Material.001** to **Material**
 
- Renaming the shadowcast material from **c_m_shadowcast -26206** to **c_m_shadowcast**
 
- Renaming the eye white material from **cf_m_sirome_00 -269114** to **cf_m_sirome_00.001**
 
- Renaming the body material from **cm_m_body -26180** to **cf_m_body**

**Comment by MediaMoots** [comment]
spider...
![image](https://user-images.githubusercontent.com/81146974/190903122-a7125c6b-11a4-41b8-b027-54bfff879969.png)

jk jk

So, this card was made by scaling down the leg bones to hide them.

@FlailingFog 
But it seems the importer deletes these bones because of the scale?


In any case you can import it with the latest version of KKBP (Blender 3.3) with these settings:
![image](https://user-images.githubusercontent.com/81146974/190903442-7e4b3742-adf8-4eee-81f1-c963a203f769.png)

![image](https://user-images.githubusercontent.com/81146974/190903449-9f884bb4-5a65-480f-adfe-a22a00d2e771.png)
